# 1. Create a null vector of size 10 but the fifth value which is 1.


In [2]:
import numpy as np
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# 2.Create a vector with values ranging from 10 to 49.

In [3]:
x=np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# 3. Create a 3x3 matrix with values ranging from 0 to 8

In [6]:
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 4. Find indices of non-zero elements from [1,2,0,0,4,0]


In [8]:
x=np.array([1,2,0,0,4,0])
a=np.nonzero(x)
a

(array([0, 1, 4], dtype=int64),)

# 5 Create a 10x10 array with random values and find the minimum and maximum values.


In [20]:
x=np.random.randint(200,size=(10,10))
print(x)
print("max value is",x.max())
print("min value is",x.min())

[[ 26 136 138   9  85  80  29 105  26 193]
 [142  28 120  51  64  60   8  68  66 176]
 [ 38  36  40  38  34 124  59 126 118 137]
 [104 155 112  48  30 166 156 139 121 179]
 [113 132  83  54  27 168 116  56  47  37]
 [144  18 199  10  24 115  31 194  80 185]
 [161 111 185 154 170  77 181 189 182 100]
 [ 55 173 101 151 199  57  83 180  41  93]
 [154 124 171  59 198  27  58  80  56 106]
 [ 62 117  99 167  25 197 170  46  49  72]]
max value is 199
min value is 8


# 6. Create a random vector of size 30 and find the mean value.


In [26]:
x=np.arange(30)
print(x)
print("mean value o array is" ,x.mean())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
mean value o array is 14.5
